version: '3.8'
services:
  bank-config-service:
    build: ./bank-config-service
    ports: 
      -"8080:8080" #le premier port c'est le port de l'application et le deuxième est le port d'ecoute
    environment:
      - SPRING_APPLICATION_NAME = bank-config-service
      - SERVER_PORT = 8000
      - SPRING_CLOUD_CONFIG_SERVER_GIT_URI = https://github.com/ArianeTchinda/Bank.git
    networks:
      - banking-network
    
  mysql_db:
    image: mysql:8
    environemnt: 
      - MYSQL_ROOT_PASSWORD = root
      - MYSQL_DATABASE = user_db
    ports:
      - "3306:3307"
    networks:
      - bank-network

  bank-registry-service:
    build: ./bank-registry-service
    ports: 
      -"8761:8080" #le premier port c'est le port de l'application et le deuxième est le port d'ecoute
    environment:
      - SPRING_APPLICATION_NAME = bank-registry-service
      - SPRING_CLOUD_CONFIG_SERVER_GIT_URI = https://bank-config-service:8080
      - SPRING_CONFIG_IMPORT =  configserver://bank-config-service:8080
    networks:
      - bank-network

  bank-proxy-service:
    build: ./bank-proxy-service
    ports: 
      -"8761:8080" #le premier port c'est le port de l'application et le deuxième est le port d'ecoute
    environment:
      - SPRING_APPLICATION_NAME = bank-registry-service
      - SPRING_CLOUD_CONFIG_SERVER_GIT_URI = https://bank-config-service:8080
      - SPRING_CONFIG_IMPORT =  configserver://bank-config-service:8080
    networks:
      - bank-network

  bank-user-service:
    build: ./bank-user-service
    ports: 
      -"8761:8080" #le premier port c'est le port de l'application et le deuxième est le port d'ecoute
    environment:
      - SPRING_APPLICATION_NAME = bank-user-service
      - SPRING_CLOUD_CONFIG_SERVER_GIT_URI = https://bank-config-service:8080
      - SPRING_CONFIG_IMPORT =  configserver://bank-config-service:8080
    networks:
      - banking-network

networks:
  bank-network:
    driver: bridge